# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-CountryFlags
version:      1.00
version_from: CountryFlags.pm
installdirs:  site
requires:
    File::SafeDO:                  0.11
    LWP::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
